request code:
  model: model/*.yml
  template: template/request.py.mako
  output: "{pwd}/{template_name}_{entity_name}.py"

request test:
  model: model/*.yml
  template: template/test_request.py.mako
  output: "{pwd}/{template_name}_{entity_name}.py"
